version: "3"
services:
  fastapi-boilerplate:
    image: matija2209/fastapi-boilerplate
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
    ports:
      - "4853:80"
